apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kcd-demo-app
spec:
  destination:
    name: ''
    namespace: demo
    server: 'https://kubernetes.default.svc'
  source:
    path: kubernetes/manifests
    repoURL: 'https://github.com/shaekhhasanshoron/kcd-demo-app'
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated: null
    syncOptions:
      - CreateNamespace=true
